import Link from "next/link";
import SiteShell from "@/components/site/SiteShell";
import PageHero from "@/components/site/PageHero";

export default function AboutPage() {
  return <SiteShell><PageHero label="About the consultancy" title="Immigration guidance grounded in clarity." copy="This is polished placeholder copy for an immigration team that values careful preparation, honest advice, and support that respects the importance of every decision." image="/assets/images/immigration/family-arrival.jpg" imageAlt="Family walking through their new neighbourhood" />
    <section className="ns-section"><div className="ns-container ns-split"><img src="/assets/images/immigration/consultation.jpg" alt="Immigration consultation in progress"/><div><span className="ns-label">Our approach</span><h2>Good advice begins with listening.</h2><p>We take time to understand the person behind the application: their education, work history, family responsibilities, deadlines, and long-term goals. The result is a strategy that is easier to understand and easier to act on.</p><p>This demonstration content is intentionally realistic but generic, ready to be replaced with the firm&apos;s actual history, registrations, and professional credentials.</p><div className="ns-checks"><span>Practical recommendations</span><span>Transparent communication</span><span>Evidence-led preparation</span><span>Respect for every client</span></div><Link href="/contact" className="ns-button">Meet with an adviser</Link></div></div></section>
    <section className="ns-section ns-section--soft"><div className="ns-container"><div className="ns-section-head"><div><span className="ns-label">What guides us</span><h2>A professional standard clients can feel.</h2></div></div><div className="ns-card-grid"><article className="ns-card"><span className="ns-card__number">01</span><h3>Clarity</h3><p>We explain complex requirements in plain language and confirm the next action in writing.</p></article><article className="ns-card"><span className="ns-card__number">02</span><h3>Integrity</h3><p>We discuss risks and limitations openly. A strong relationship is built on realistic expectations.</p></article><article className="ns-card"><span className="ns-card__number">03</span><h3>Care</h3><p>Every application represents a real life decision, so details and communication both matter.</p></article></div></div></section>
  </SiteShell>;
}
